"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](bg:red)\
$os\
$username\
[](bg:peach fg:red)\
$directory\
[](fg:peach bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$nodejs\
$golang\
$ruby\
$rust\
[](fg:green bg:sapphire)\
$docker_context\
[](fg:sapphire bg:lavender)\
$time\
[](fg:lavender)\
$line_break$character"""

palette = 'kanagawa_wave'

[os]
disabled = false
style = "bg:red fg:crust"

[os.symbols]
Macos = "󰀵"
Linux = "󰌽"

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user ]($style)'

[directory]
style = "fg:crust bg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:crust bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:crust bg:yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[ruby]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[ $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'

# ~~~ theme palette (managed by `theme`, do not edit below) ~~~
[palettes.kanagawa_wave]
red = "#E46876"
peach = "#FFA066"
yellow = "#E6C384"
green = "#98BB6C"
sapphire = "#7E9CD8"
lavender = "#957FB8"
text = "#DCD7BA"
crust = "#16161D"
